[program:ftpserver]
command=/usr/local/bin/ftpserver -conf /app/ftpserver.json
directory=/app
user=www-data
autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=5
stderr_logfile=/var/log/ftpserver_error.log
stdout_logfile=/var/log/ftpserver.log
priority=1
